import { StyleSheet, Platform, Dimensions } from 'react-native';
import { Theme } from '../types/index';

const { width } = Dimensions.get('window');

export const getAddEntryStyles = (theme: Theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme === 'light' ? '#f8f9fa' : '#121212',
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 100,
  },
  title: {
    fontSize: 30,
    fontWeight: '800',
    marginBottom: 28,
    color: theme === 'light' ? '#333' : '#f0f0f0',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  cameraButton: {
    backgroundColor: '#6200ee',
    padding: 18,
    borderRadius: 16,
    alignItems: 'center',
    marginBottom: 28,
    flexDirection: 'row',
    justifyContent: 'center',
    elevation: 6,
    shadowColor: '#6200ee',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
  },
  buttonIcon: {
    marginRight: 10,
  },
  cameraButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  previewContainer: {
    marginBottom: 24,
    backgroundColor: theme === 'light' ? 'white' : '#1e1e1e',
    borderRadius: 16,
    overflow: 'hidden',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
  },
  image: {
    width: '100%',
    height: 280,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  inputContainer: {
    padding: 18,
    borderBottomWidth: 1,
    borderBottomColor: theme === 'light' ? '#eee' : '#333',
  },
  inputLabel: {
    fontWeight: '700',
    color: theme === 'light' ? '#444' : '#ddd',
    fontSize: 16,
    marginBottom: 10,
    letterSpacing: 0.3,
  },
  textInput: {
    backgroundColor: theme === 'light' ? '#f8f8f8' : '#252525',
    borderRadius: 12,
    padding: 14,
    color: theme === 'light' ? '#333' : '#eee',
    fontSize: 16,
    borderWidth: 1,
    borderColor: theme === 'light' ? '#e0e0e0' : '#444',
  },
  notesInput: {
    minHeight: 120,
    maxHeight: 200,
    textAlignVertical: 'top',
    lineHeight: 22,
  },
  addressContainer: {
    padding: 18,
    backgroundColor: theme === 'light' ? '#f8f8f8' : '#252525',
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
  },
  addressHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  addressLabel: {
    fontWeight: '700',
    marginLeft: 8,
    color: theme === 'light' ? '#444' : '#ddd',
    fontSize: 16,
    letterSpacing: 0.3,
  },
  addressText: {
    color: theme === 'light' ? '#333' : '#eee',
    marginBottom: 14,
    fontSize: 15,
    lineHeight: 22,
  },
  coordinatesContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme === 'light' ? 'rgba(0,0,0,0.03)' : 'rgba(255,255,255,0.05)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  coordIcon: {
    marginRight: 6,
  },
  coordinatesText: {
    color: theme === 'light' ? '#666' : '#aaa',
    fontSize: 12,
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace' }),
  },
  noAddressText: {
    color: theme === 'light' ? '#666' : '#aaa',
    fontStyle: 'italic',
    marginBottom: 8,
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: theme === 'light' ? 'rgba(255, 255, 255, 0.98)' : 'rgba(30, 30, 30, 0.98)',
    padding: 16,
    paddingHorizontal: 20,
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: theme === 'light' ? '#e0e0e0' : '#333',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  saveButton: {
    backgroundColor: '#4caf50',
    padding: 16,
    borderRadius: 14,
    alignItems: 'center',
    flex: 3,
    flexDirection: 'row',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: '#4caf50',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  saveButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  cancelButton: {
    backgroundColor: theme === 'light' ? '#f5f5f5' : '#2c2c2c',
    padding: 16,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    marginRight: 12,
    borderWidth: 1,
    borderColor: theme === 'light' ? '#e0e0e0' : '#444',
  },
  cancelButtonText: {
    color: theme === 'light' ? '#666' : '#bbb',
    fontSize: 16,
    fontWeight: '600',
  },
  loadingContainer: {
    alignItems: 'center',
    marginVertical: 28,
  },
  loadingText: {
    marginTop: 14,
    color: theme === 'light' ? '#666' : '#aaa',
    fontSize: 16,
  },
  headerBackButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  headerBackText: {
    color: 'white',
    fontSize: 16,
    marginLeft: Platform.OS === 'ios' ? 4 : 0,
    display: Platform.OS === 'ios' ? 'flex' : 'none',
    fontWeight: '600',
  },
});